flags:
  prod:
    setup: false
    users: true
    ssh: false
    fail2ban: false
    alerting: false
    backblaze: false
    mysql: false
    nginx: false
    docker: false
    pterodactyl: false
    wings: false
    mongodb: false
    bind9: false
    mail: true
    logwatch: false
    crowdsec: true