- name: Add scripts/docker folder
  ansible.builtin.file:
    path: /scripts/docker
    state: directory
    mode: '0755'
  become: true

- name: Install apt dependencies
  apt:
    pkg: 
      - ca-certificates
      - curl
    state: latest
    update_cache: false
  become: true

- name: Make sure /etc/apt/keyrings is available
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Download Docker keyring
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0444'
  become: true

- name: Get system architecture
  ansible.builtin.shell: 'dpkg --print-architecture'
  register: dpkg_architecture
  become: true
  check_mode: false

- name: Get version codename
  ansible.builtin.shell: '. /etc/os-release && echo "$VERSION_CODENAME"'
  register: version_codename
  become: true
  check_mode: false

- name: Add Docker repository to apt sources
  ansible.builtin.template:
    src: ../files/docker.list
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Install Docker
  apt:
    pkg: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: latest
    update_cache: true
  become: true

- name: Enable Docker
  ansible.builtin.systemd:
    name: docker.service
    state: started
    scope: system
    enabled: true
  become: true