- name: Create PostfixAdmin webroot
  ansible.builtin.file:
    path: '/var/www/postfixadmin'
    state: directory
    mode: '0755'
  become: true

- name: Download PostfixAdmin
  ansible.builtin.get_url:
    url: "{{ mail['postfixadmin']['download'] }}"
    dest: '/var/www/postfixadmin/postfixadmin.tar.gz'
    mode: '0700'
  register: postfixadmin_download
  become: true

- name: Extract PostfixAdmin into /var/www/postfixadmin
  ansible.builtin.unarchive:
    src: '/var/www/postfixadmin/postfixadmin.tar.gz'
    dest: '/var/www/postfixadmin'
    remote_src: true
    mode: '0755'
  when: postfixadmin_download.changed
  become: true

- name: Move PostfixAdmin files into webroot
  ansible.builtin.shell: "mv /var/www/postfixadmin/postfixadmin-postfixadmin-{{ mail['postfixadmin']['version'] }}/* /var/www/postfixadmin"
  when: postfixadmin_download.changed
  become: true

- name: Remove PostfixAdmin extract
  ansible.builtin.command: "rm -r /var/www/postfixadmin/postfixadmin-postfixadmin-{{ mail['postfixadmin']['version'] }}"
  when: postfixadmin_download.changed
  become: true

- name: Create PostfixAdmin templates folder
  ansible.builtin.file:
    path: '/var/www/postfixadmin/templates_c'
    state: directory
    mode: '0775'
  register: postfixadmin_templates
  become: true

- name: Set acl for PostfixAdmin templates folder
  ansible.builtin.command: "setfacl -R -m u:www-data:rwx /var/www/postfixadmin/templates_c/"
  when: postfixadmin_templates.changed
  become: true

- name: Set acl for PostfixAdmin Let's Encrypt keys
  ansible.builtin.command: "setfacl -R -m u:www-data:rx /etc/letsencrypt/live/ /etc/letsencrypt/archive/"
  when: postfixadmin_templates.changed
  become: true

- name: Create PostfixAdmin SQL database
  community.mysql.mysql_db:
    name: "{{ mail['postfixadmin']['sql_db'] }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    state: present
  become: true

- name: Create PostfixAdmin SQL user
  community.mysql.mysql_user:
    name: "{{ mail['postfixadmin']['sql_user'] }}"
    password: "{{ mail['postfixadmin']['sql_password'] }}"
    login_host: "127.0.0.1"
    priv: "{{ mail['postfixadmin']['sql_db'] }}.*:ALL"
    login_unix_socket: /run/mysqld/mysqld.sock
    column_case_sensitive: true
    state: present
  become: true

# We store this as a file so we don't get the noise of a changed hash
# (and also changed config file) whenever this runs. 
- name: Stat PostfixAdmin hash
  ansible.builtin.stat: 
    path: /var/www/postfixadmin/_pwh.txt
  become: true
  register: pfa_hash_file

- name: Generate PostfixAdmin setup password hash
  ansible.builtin.shell: >-
    php -r 'echo password_hash("{{ mail["postfixadmin"]["setup_password"] }}", PASSWORD_DEFAULT);' > /var/www/postfixadmin/_pwh.txt
  when: not pfa_hash_file.stat.exists
  become: true

- name: Get the PostfixAdmin hash
  ansible.builtin.slurp: 
    src: /var/www/postfixadmin/_pwh.txt
  become: true
  register: pfa_hash_file_content

- name: Add templated config file config.local.php
  ansible.builtin.template:
    src: ../files/postfixadmin/config.local.php
    dest: /var/www/postfixadmin/config.local.php
    owner: root
    group: root
    mode: '0744'
  become: true
  register: config_local_php_file

- name: Create nginx site file
  ansible.builtin.template:
    src: ../files/postfixadmin/nginx
    dest: /etc/nginx/sites-available/{{ hostname }}-postfixadmin
    owner: root
    group: root
    mode: "0744"
  become: true
  register: nginx_site

- name: Create symlink for nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ hostname }}-postfixadmin
    dest: /etc/nginx/sites-enabled/{{ hostname }}-postfixadmin
    owner: root
    group: root
    mode: "0744"
    state: link
  become: true

- name: Verify nginx site file
  ansible.builtin.command: nginx -t
  become: true
  when: nginx_site.changed

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx.service
    state: restarted
    scope: system
    enabled: true
  become: true
  when: nginx_site.changed
