- name: Add scripts folder
  ansible.builtin.file:
    path: /scripts
    state: directory
    mode: '0755'
  become: true
- name: Set hostname
  ansible.builtin.hostname: 
    name: '{{ hostname }}'
  become: true