- name: Install Duplicity
  import_tasks: dependencies.yml

- name: Apply flag-based backup paths
  import_tasks: apply_vars.yml

- name: Create Duplicity systemd backup timer
  import_tasks: service.yml