- hosts: all
  remote_user: root
  vars_files:
    - vars/flags.yml
    - vars/dependency_versions.yml
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: true
    - name: Add state folder
      ansible.builtin.file:
        path: /state
        state: directory
        mode: '0755'
      become: true
    - name: Get the current time
      ansible.builtin.shell: TZ=America/Chicago date "+%m/%d/%Y at %r (%Z)"
      register: current_time
    - name: Write latest deploy time to file
      ansible.builtin.template:
        src: files/last_deploy
        dest: /state/last_deploy
        owner: root
        group: root
        mode: '0644'
      become: true
    - name: Primary node setup
      include_role:
        name: setup
      when: flags[env]['setup']
    - name: Users
      include_role:
        name: users
      when: flags[env]['users']
    - name: SSH
      include_role:
        name: ssh
      when: flags[env]['ssh']
    - name: Fail2ban
      include_role:
        name: fail2ban
      when: flags[env]['fail2ban']
    - name: Alerting
      include_role:
        name: alerting
      when: flags[env]['alerting']
    - name: Backblaze B2 backups
      include_role:
        name: backblaze
      when: flags[env]['backblaze']
    - name: MySQL
      include_role:
        name: mysql
      when: flags[env]['mysql']
    - name: Nginx
      include_role:
        name: nginx
      when: flags[env]['nginx']
    - name: Docker
      include_role:
        name: docker
      when: flags[env]['docker']
    - name: Pterodactyl
      include_role:
        name: pterodactyl
      when: flags[env]['docker'] and flags[env]['pterodactyl']
    - name: Wings
      include_role:
        name: wings
      when: flags[env]['docker'] and flags[env]['wings']
    - name: MongoDB
      include_role:
        name: mongodb
      when: flags[env]['mongodb']
    - name: Bind9
      include_role:
        name: bind9
      when: flags[env]['bind9']
    - name: Mail
      include_role:
        name: mail
      when: flags[env]['mail']
    - name: Logwatch
      include_role:
        name: logwatch
      when: flags[env]['logwatch']
    - name: CrowdSec
      include_role:
        name: crowdsec
      when: flags[env]['crowdsec']