- hosts: all
  remote_user: root
  tasks:
    - name: Parse 'only_deploy' (-e only_deploy=...) list
      set_fact: 
        only_deploy_list: "{{ only_deploy | split(',') }}"
      when: only_deploy is defined
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: true
    - name: Add state folder
      ansible.builtin.file:
        path: /state
        state: directory
        mode: '0755'
      become: true
    - name: Get the current time
      ansible.builtin.shell: TZ=America/Chicago date "+%m/%d/%Y at %r (%Z)"
      register: current_time
    - name: Write latest deploy time to file
      ansible.builtin.template:
        src: files/last_deploy
        dest: /state/last_deploy
        owner: root
        group: root
        mode: '0644'
      become: true
    - name: Primary node setup
      include_role:
        name: setup
      when: flags['setup'] and (only_deploy_list is not defined or 'setup' in only_deploy_list)
    - name: Users
      include_role:
        name: users
      when: flags['users'] and (only_deploy_list is not defined or 'users' in only_deploy_list)
    - name: SSH
      include_role:
        name: ssh
      when: flags['ssh'] and (only_deploy_list is not defined or 'ssh' in only_deploy_list)
    - name: Fail2ban
      include_role:
        name: fail2ban
      when: flags['fail2ban'] and (only_deploy_list is not defined or 'fail2ban' in only_deploy_list)
    - name: Alerting
      include_role:
        name: alerting
      when: flags['alerting'] and (only_deploy_list is not defined or 'alerting' in only_deploy_list)
    - name: Backblaze B2 backups
      include_role:
        name: backblaze
      when: flags['backblaze'] and (only_deploy_list is not defined or 'backblaze' in only_deploy_list)
    - name: MySQL
      include_role:
        name: mysql
      when: flags['mysql'] and (only_deploy_list is not defined or 'mysql' in only_deploy_list)
    - name: Nginx
      include_role:
        name: nginx
      when: flags['nginx'] and (only_deploy_list is not defined or 'nginx' in only_deploy_list)
    - name: Docker
      include_role:
        name: docker
      when: flags['docker'] and (only_deploy_list is not defined or 'docker' in only_deploy_list)
    - name: Pterodactyl
      include_role:
        name: pterodactyl
      when: flags['docker'] and flags['pterodactyl'] and (only_deploy_list is not defined or 'pterodactyl' in only_deploy_list)
    - name: Wings
      include_role:
        name: wings
      when: flags['docker'] and flags['wings'] and (only_deploy_list is not defined or 'wings' in only_deploy_list)
    - name: MongoDB
      include_role:
        name: mongodb
      when: flags['mongodb'] and (only_deploy_list is not defined or 'mongodb' in only_deploy_list)
    - name: Bind9
      include_role:
        name: bind9
      when: flags['bind9'] and (only_deploy_list is not defined or 'bind9' in only_deploy_list)
    - name: Mail
      include_role:
        name: mail
      when: flags['mail'] and (only_deploy_list is not defined or 'mail' in only_deploy_list)
    - name: Logwatch
      include_role:
        name: logwatch
      when: flags['logwatch'] and (only_deploy_list is not defined or 'logwatch' in only_deploy_list)
    - name: CrowdSec
      include_role:
        name: crowdsec
      when: flags['crowdsec'] and (only_deploy_list is not defined or 'crowdsec' in only_deploy_list)