- hosts: all
  remote_user: root
  tasks:
    - name: Parse 'only_deploy' (-e only_deploy=...) list
      set_fact: 
        only_deploy: "{{ only_deploy | split(',') }}"
      when: only_deploy is defined
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: true
    - name: Add state folder
      ansible.builtin.file:
        path: /state
        state: directory
        mode: '0755'
      become: true
    - name: Get the current time
      ansible.builtin.shell: TZ=America/Chicago date "+%m/%d/%Y at %r (%Z)"
      register: current_time
    - name: Write latest deploy time to file
      ansible.builtin.template:
        src: files/last_deploy
        dest: /state/last_deploy
        owner: root
        group: root
        mode: '0644'
      become: true
    - name: Primary node setup
      include_role:
        name: setup
      when: flags['setup'] and (dep_list is not defined or dep_list['setup'])
    - name: Users
      include_role:
        name: users
      when: flags['users'] and (dep_list is not defined or dep_list['users'])
    - name: SSH
      include_role:
        name: ssh
      when: flags['ssh'] and (dep_list is not defined or dep_list['ssh'])
    - name: Fail2ban
      include_role:
        name: fail2ban
      when: flags['fail2ban'] and (dep_list is not defined or dep_list['fail2ban'])
    - name: Alerting
      include_role:
        name: alerting
      when: flags['alerting'] and (dep_list is not defined or dep_list['alerting'])
    - name: Backblaze B2 backups
      include_role:
        name: backblaze
      when: flags['backblaze'] and (dep_list is not defined or dep_list['backblaze'])
    - name: MySQL
      include_role:
        name: mysql
      when: flags['mysql'] and (dep_list is not defined or dep_list['mysql'])
    - name: Nginx
      include_role:
        name: nginx
      when: flags['nginx'] and (dep_list is not defined or dep_list['nginx'])
    - name: Docker
      include_role:
        name: docker
      when: flags['docker'] and (dep_list is not defined or dep_list['docker'])
    - name: Pterodactyl
      include_role:
        name: pterodactyl
      when: flags['docker'] and flags['pterodactyl'] and (dep_list is not defined or dep_list['pterodactyl'])
    - name: Wings
      include_role:
        name: wings
      when: flags['docker'] and flags['wings'] and (dep_list is not defined or dep_list['wings'])
    - name: MongoDB
      include_role:
        name: mongodb
      when: flags['mongodb'] and (dep_list is not defined or dep_list['mongodb'])
    - name: Bind9
      include_role:
        name: bind9
      when: flags['bind9'] and (dep_list is not defined or dep_list['bind9'])
    - name: Mail
      include_role:
        name: mail
      when: flags['mail'] and (dep_list is not defined or dep_list['mail'])
    - name: Logwatch
      include_role:
        name: logwatch
      when: flags['logwatch'] and (dep_list is not defined or dep_list['logwatch'])
    - name: CrowdSec
      include_role:
        name: crowdsec
      when: flags['crowdsec'] and (dep_list is not defined or dep_list['crowdsec'])