name: Apply Latest to Prod

on:
  workflow_dispatch: {}

env:
  SSH_KEY_DEV: ${{ secrets.SSH_KEY_DEV }}
  SSH_HOST_DEV: ${{ secrets.SSH_HOST_DEV }}
  SSH_USER_DEV: ${{ secrets.SSH_USER_DEV }}

  SSH_KEY_PROD: ${{ secrets.SSH_KEY_PROD }}
  SSH_HOST_PROD: ${{ secrets.SSH_HOST_PROD }}
  SSH_USER_PROD: ${{ secrets.SSH_USER_PROD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - name: Prepare to run Ansible
        run: . main/ci/scripts/prep.sh
      - name: Execute Ansible playbook (PROD)
        run: . main/ci/scripts/ansible-execute.sh PROD