name: Apply Push to Dev

on:
  push:
    branches:
      - main

env:
  SSH_KEY_DEV: ${{ secrets.SSH_KEY_DEV }}
  SSH_HOST_DEV: ${{ secrets.SSH_HOST_DEV }}
  SSH_USER_DEV: ${{ secrets.SSH_USER_DEV }}

  SSH_KEY_PROD: ${{ secrets.SSH_KEY_PROD }}
  SSH_HOST_PROD: ${{ secrets.SSH_HOST_PROD }}
  SSH_USER_PROD: ${{ secrets.SSH_USER_PROD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - name: Prepare to run Ansible
        run: . main/ci/scripts/common-setup.sh
      - name: Execute Ansible playbook (DEV)
        run: . main/ci/scripts/ansible-execute.sh DEV